apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniproject-deployment
  labels:
    app: miniproject
spec:
  replicas: 2
  selector:
    matchLabels:
      app: miniproject
  template:
    metadata:
      labels:
        app: miniproject
    spec:
      containers:
      - name: miniproject-client
        image: boudhraadhia7/miniproject01:latest # Use the correct image tag
        ports:
        - containerPort: 3000 # Replace with the port your app listens on
