apiVersion: v1
kind: Service
metadata:
  name: miniproject-service
spec:
  selector:
    app: miniproject
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000 # This should match the containerPort from your deployment
  type: LoadBalancer # This will make your service accessible from the internet
