apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 3001
  type: LoadBalancer
  selector:
    app: backend
